### ISSUE TITLE
run AQL in remote method

### ISSUE THREAD

**Issue by reidlaiatags** [mrbatista/loopback-connector-arangodb#39] opened 2016-12-20 14:49 UTC
Any example to show how to run AQL in loopback remote method?

**Comment by mrbatista** [comment] 2016-12-20 14:59
@reidlaiatags See https://github.com/mrbatista/loopback-connector-arangodb/blob/master/test/core.test.coffee#L190

**Comment by mrbatista** [comment] 2017-01-31 15:35
@codeyad I am closing the issue as resolved. If the issue is still persisting, please fell free to leave a comment and I will re-open the issue. Thanks.

**Comment by mrbatista** [comment] 2017-01-31 15:36
@reidlaiatags I am closing the issue as resolved. If the issue is still persisting, please fell free to leave a comment and I will re-open the issue. Thanks.

**Closed by mrbatista** 2017-01-31 15:35 UTC
